# API URLs
FOTOR_OPENAPI_VALIDATE_API_KEY = "/v1/aiart/credentials"
FOTOR_OPENAPI_TASK_STATUS_URL = "/v1/aiart/tasks"
FOTOR_OPENAPI_UPSCALER_URL = "/v1/aiart/imgupscale"
FOTOR_OPENAPI_RETOUCH_URL = "/v1/aiart/retouchskin"
FOTOR_OPENAPI_TXT2IMG_URL = "/v1/aiart/text2img"
FOTOR_OPENAPI_IMG2IMG_URL = "/v1/aiart/img2img"
FOTOR_OPENAPI_REMBG_URL = "/v1/aiart/backgroundremover"
FOTOR_OPENAPI_HEADSHOT_URL = "/v1/aiart/avatar"
FOTOR_OPENAPI_COLORIZE_URL = "/v1/aiart/colorize"
FOTOR_OPENAPI_RESTORATION_URL = "/v1/aiart/restoration"
FOTOR_OPENAPI_FACESWAP_URL = "/v1/aiart/faceswap"
FOTOR_OPENAPI_IMG2VIDEO_URL = "/v1/aiart/img2video"
FOTOR_OPENAPI_CHARACTER2VIDEO_URL = "/v1/aiart/character2video"
FOTOR_OPENAPI_FACE_CUTOUT_URL = "/v1/aiart/facecutout"
FOTOR_OPENAPI_REPLACER_URL= "/v1/aiart/replacer"